package com.boot.utils;

import java.util.HashMap;
import java.util.Map;

public class AutoCodeMain {

    /**
     *
     */
    public static void main(String[] args) throws Exception {

//        autoCreateCode();
        autoAddCode();

    }

    private static void autoCreateCode () throws Exception{

        //表名
        String[] tableNames = new String[]{"user_api"};


        ConnDB ysConnDB = new ConnDB("com.mysql.jdbc.Driver", "jdbc:mysql://10.1.1.3:3306", "ys", "root", "root");
        String packageName = "com.boot";
        //模板路径
        String templateDir = (AutoCodeMain.class.getResource("/") + "template").substring(6);

        //生成文件路径
        String srcFile = "F:\\autoGenerated";
        //实例化
        AutoCodeUtils autoGenerationJavaCode = new AutoCodeUtils(ysConnDB, packageName, tableNames, srcFile, templateDir);

        //调用生成java代码方法
        autoGenerationJavaCode.autoCreateCode();
    }

    private static void autoAddCode () throws Exception{

        //表名
        String[] tableNames = new String[]{"user_api"};

        ConnDB ysConnDB = new ConnDB("com.mysql.jdbc.Driver", "jdbc:mysql://10.1.1.3:3306", "ys", "root", "root");
        String packageName = "com.boot";
        //模板路径
        String templateDir = (AutoCodeMain.class.getResource("/") + "template").substring(6);

        //生成文件路径
        String srcFile = "F:\\autoGenerated";
        //实例化
        AutoCodeUtils autoGenerationJavaCode = new AutoCodeUtils(ysConnDB, packageName, tableNames, srcFile, templateDir);


        //设置模板内容
        Map<String, Object> rootMap = new HashMap<String, Object>();
        // 方法设置 list_one
        rootMap.put("method", new Field("UserApi","select_more","用户"));
        // 参数设置
        Map<String, Field> args = new HashMap<>();
        args.put("pone",new Field("userName","String","用户名"));
        args.put("ptwo",new Field("sex","String","性别"));
        args.put("pthree",new Field("age","int","年龄"));
        rootMap.put("args", args);

        //调用生成java代码方法
        autoGenerationJavaCode.autoAddCode("UserApi",rootMap);
    }
}
